get:
  operationId: get_hosts
  summary: Get cluster/discovered hosts
  description: |
    Returns the list of administrative cluster hosts. It is also possible to
    return the list of hosts that have been discovered using multicast 
    advertisment.

    In order to retrive discovered hosts set the `discovered` query string to
    `true`. This request can be executed unauthorized as long as there are
    no admin users.
  x-onedata-version: 3
  x-onedata-module: rest_onepanel
  x-onedata-resource: hosts
  x-onedata-noauth: true
  tags:
    - Onepanel
  produces:
    - application/json
  responses:
    '200':
      description: The list of administrative cluster hosts.
      schema:
        type: array
        description: List of cluster or discovered hosts.
        items: 
          type: string
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
  parameters:
    - name: discovered
      in: query
      description: Defines whether return cluster or discovered hosts.
      type: boolean
      default: false
      required: false

put:
  operationId: put_hosts
  summary: Create or join cluster
  description: |
    Initializes administrative cluster or if `clusterHost` parameter has been
    provided in the query string adds this host to an existing cluster.

    In case of cluster initialization this request removes all user and
    configuration data. This request can be executed unauthorized as long as
    there are no admin users.
  x-onedata-version: 3
  x-onedata-module: rest_onepanel
  x-onedata-resource: hosts
  x-onedata-noauth: true
  tags:
    - Onepanel
  consumes:
    - application/json
  responses:
    '204':
      description: Cluster has been successfully initialized or extended.
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
  parameters:
    - name: clusterHost
      in: query
      description: Hostname of an existing cluster node.
      type: string
      required: false