get:
  operationId: get_hosts
  x-onedata-version: 3
  x-onedata-module: rest_onepanel
  x-onedata-resource: hosts
  x-onedata-noauth: true
  tags:
    - Onepanel
  summary: Get cluster hosts
  description: |
    Returns the list of hosts in the local Onedata deployment.
  produces:
    - application/json
  responses:
    '200':
      description: Returns the list of Onedata nodes.
      schema:
        type: array
        items: 
          type: string
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Onepanel service not found. 
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: discovered
    in: query
    description: Whether we should add automatically discovered nodes.
    type: boolean
    default: false
    required: false

put:
  operationId: add_hosts
  x-onedata-version: 3
  x-onedata-module: rest_onepanel
  x-onedata-resource: hosts
  x-onedata-noauth: true
  tags:
    - Onepanel
  summary: Add cluster hosts
  description: |
    Allows to set the list of nodes in the local Onedata deployment.
  consumes:
    - application/json
  responses:
    '204':
      description: List of Onedata nodes changed successfully.
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Onepanel service not found. 
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: hosts
    in: body
    schema:
      $ref: '#/definitions/Hosts'
    required: true
  - name: discovered
    in: query
    description: Whether we should add automatically discovered nodes.
    type: boolean
    required: false
    default: false

