get:
  operationId: provider_get_configuration
  x-onedata-service: oneprovider
  x-onedata-module: installer
  x-onedata-method: get_configuration
  summary: Get provider configuration.
  description: Returns the current Oneprovider service configuration.
  tags:
    - Provider
  produces:
    - application/x-yaml
  responses:
    '200':
      description: Current Oneprovider configuration in YAML format.
      schema:
        type: string
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Oneprovider service configuration is not available. 
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'

post:
  operationId: provider_configure
  x-onedata-service: oneprovider
  x-onedata-module: installer
  x-onedata-method: install
  tags:
    - Provider
  summary: Modify provider configuration.
  description: >
   Updates the current Oneprovider service configuration.
  consumes:
    - application/x-yaml
  responses:
    '200':
      description: Configuration updated successfully
      schema:
        type: string
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Oneprovider service configuration is not available. 
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: configuration
    in: body
    description: New Oneprovider configuration in YAML format.
    schema:
      type: string
      format: yaml
    required: true

