
put:
  operationId: modify_zone_configuration
  summary: Update zone configuration
  description: |
    Updates the current configuration of Onedata service deployment. 
    Depending on the type of service managed by the Onepanel, 
    it accepts Onezone configuration description.
  x-onedata-version: 3
  x-onedata-module: rest_service
  x-onedata-resource: service_onezone
  tags:
    - Onezone
  consumes:
    - application/x-yaml
  responses:
    '204':
      description: Onezone service configuration updated successfully.
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Onepanel service is not available.
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: configuration
    in: body
    description: New deployment configuration.
    schema:
      $ref: '#/definitions/OnezoneConfiguration'
    required: true
    