get:
  operationId: zone_get_configuration
  x-onedata-service: onezone
  x-onedata-module: installer
  x-onedata-method: get_configuration
  summary: Get Onezone configuration.
  description: Returns the current Onezone service configuration.
  tags:
    - Zone
  produces:
    - application/x-yaml
  responses:
    '200':
      description: Current Onezone configuration in YAML format.
      schema:
        type: string
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Onezone service configuration is not available. 
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'

post:
  operationId: zone_configure
  x-onedata-service: onezone
  x-onedata-module: installer
  x-onedata-method: install
  tags:
    - Zone
  summary: Modify Onezone configuration.
  description: >
   Updates the current Onezone service configuration.
  consumes:
    - application/x-yaml
  responses:
    '200':
      description: Configuration updated successfully
      schema:
        type: string
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
      schema:
        $ref: '#/definitions/Error'
    '404':
      description: Onezone service configuration is not available. 
      schema:
        $ref: '#/definitions/Error'
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: configuration
    in: body
    description: New Onezone configuration in YAML format.
    schema:
      type: string
      format: yaml
    required: true

