put:
  operationId: put_zone_configuration
  summary: Create zone deployment
  description: |
    Configures and starts zone services, such as database, cluster manager
    and cluster worker.
  x-onedata-version: 3
  x-onedata-module: rest_service
  x-onedata-resource: service_onezone
  tags:
    - Onezone
  consumes:
    - application/json
  responses:
    '204':
      description: Deployment process successfully started.
      headers:
        Location:
          type: string
          description: |
            The path to the task resource, which can be queried to check
            operation status.
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
  parameters:
  - name: zoneConfiguration
    in: body
    schema:
      $ref: '#/definitions/ZoneConfiguration'
    required: true