swagger: '2.0'
basePath: /api/v3/onepanel
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Onepanel
    description: Onepanel API methods
securityDefinitions:
  api_key:
    type: apiKey
    name: macaroon
    in: header