type: object
description: Describes a the properties of a Database instance.
properties:
  memoryQuota:
    type: integer
    description: The maximum size of RAM memory to be used by the database instance in MB.