type: object
description: The list of hosts which should be added to the current deployment.
properties:
  hosts:
    type: array
    items:
      type: string
    x-erlang-default-value: "[]"
example:
  hosts:
    - oneprovider1.example.com
    - oneprovider2.example.com
    - oneprovider3.example.com
  