type: object
description: Oneprovider custom configuration.
required:
- cluster
properties:
  cluster:
    $ref: '#/definitions/ClusterProviderConfiguration'
  oneprovider:
    $ref: '#/definitions/Provider'
  onezone:
    type: object
    properties:
      domainName:
        type: string
    required:
    - domainName



