type: object
description: Onezone custom configuration.
required:
- cluster
properties:
  cluster:
    $ref: '#/definitions/ClusterZoneConfiguration'
  onezone:
    type: object
    properties:
      domainName:
        type: string
      name:
        type: string



