allOf:
  - $ref: '#/definitions/Configuration'
  - description: Onezone cluster configuration specific attributes.
  - properties:
      onezone:
        type: object
        properties:
          domainName:
            type: string