type: object
description: The provider cluster configuration.
properties:
  autoDeploy:
    type: boolean
    description: >
      Defines whether administrative cluster should be created from the list
      of provided cluster nodes.
  domainName:
    type: string
    description: >
      The name of a domain common for all services in the cluster. Together with
      a node hostname constitutes a fully qualified domain name (FDQN) of the node.
  nodes:
    type: object
    description: The collection of nodes aliases associated with nodes properties.
    additionalProperties:
      type: object
      properties:
        hostname:
          type: string
          description: The name of a host.
      required:
        - hostname
  databases:
    $ref: '#/definitions/ClusterDatabases'
  managers:
    $ref: '#/definitions/ClusterManagers'
  workers:
    $ref: '#/definitions/ClusterWorkers'
  storages:
    type: object
    description: The cluster storage configuration.
    additionalProperties:
      $ref: '#/definitions/ClusterStorages'
required:
  - domainName
  - nodes
  - databases
  - managers
  - workers
