type: object
description: Describes the properties of a Worker process instance.
properties:
  name:
    type: string
    description: The name under which the provider should be registered in the zone.
  redirectionPoint:
    type: string
    description: Redirection point.
  geoLongitude:
    type: number
    x-erlang-datatype: float
    default: 0.0
    description: Geographical longitude of the storage provider.
  geoLatitude:
    type: number
    x-erlang-datatype: float
    default: 0.0
    description: Geographical latitude of the storage provider.
  onezoneDomainName:
    type: string
    description: The name of Onezone domain to which this provider belongs.  
required:
  - name  
  - redirectionPoint
example:
  name: Provider1
  redirectionPoint: https://192.168.11.23:8443/
  geoLongitude: -24.3776025
  geoLatitude: -128.3519364
  onezoneDomainName: onezone2.example.com