type: object
description: >
  Settings for auto cleaning algorithms - for what files and when it should
  be started. If parameter is not set in the request, previous value will be
  used.
properties:
  lowerFileSizeLimit:
    type: integer
    description: >
      Only files which size [b] is greater than or equal to given value should be cleaned.
      Set to null to disable this parameter.
  upperFileSizeLimit:
    type: integer
    description: >
      Only files which size [b] is less than or equal to given value should be cleaned
      Set to null to disable this parameter.
  maxFileNotOpenedHours:
    type: integer
    description: >
      Files that haven't been opened for longer than or equal to given period [h] will be
      cleaned. Set to null to disable this parameter.
  threshold:
    type: integer
    description: >
      Autocleaning will start if occupancy of storage will greater than or equal to this value [b].
      This parameter is required to start autocleaning.
  target:
    type: integer
    description: >
      Autocleaning will stop if occupancy of storage will be less than or equal to this value [b].
      This parameter is required to start autocleaning.
example:
  lowerFileSizeLimit: 1000
  upperFileSizeLimit: 1000000
  maxFileNotOpenedHours: 60000
  target: 5000000000
  threshold: 6000000000
  