type: object
description: >
  Settings for auto cleaning algorithms - for what files and when it should
  be started. If parameter is not set in the request, previous value will be
  used.
properties:
  fileSizeGreaterThan:
    type: integer
    description: >
      Only files which size [b] exceeds given should be cleaned.
      Set to null to disable this parameter.
  fileSizeLessThan:
    type: integer
    description: >
      Only files which size [b] is less than given should be cleaned
      Set to null to disable this parameter.
  fileNotActiveHours:
    type: integer
    description: >
      Only files that were not active for given period [h] should be
      cleaned. Set to null to disable this parameter.
  threshold:
    type: integer
    description: >
      Autocleaning will start if occupancy of storage will exceed this value.
      This parameter is required to start autocleaning.
  target:
    type: integer
    description: >
      Autocleaning will stop if occupancy of storage will reach this value.
      This parameter is required to start autocleaning.
example:
  fileSizeGreaterThan: 1000
  fileSizeLessThan: 1000000
  fileNotActiveHours: 60000
  target: 5000000000
  threshold: 6000000000
  