type: object
description: The zone deployment configuration.
properties:
  cluster:
    $ref: '#/definitions/ZoneClusterConfiguration'
  onezone:
    type: object
    description: The zone custom configuration.
    properties:
      domainName:
        description: The name of a HTTP domain.
        type: string
      name:
        description: The name of a zone.
        type: string
  onepanel:
    $ref: '#/definitions/PanelConfiguration'
required:
  - cluster
example:
  cluster:
    domainName: "onezone.onedata.example.com"
    nodes:
      node1:
        hostname: "node1"
    manager:
      defaultNode: "node1"
      nodes:
        - "node1"
    worker:
      nodes:
        - "node1"
    database:
      nodes:
        - "node1"
  onezone:
    name: "example"
